
-- Fonction 1: GET_NB_WORKERS
CREATE OR REPLACE FUNCTION GET_NB_WORKERS(FACTORY_ID NUMBER) RETURN NUMBER IS
    total_workers NUMBER;
BEGIN
    SELECT COUNT(*) INTO total_workers
    FROM ALL_WORKERS
    WHERE FACTORY_ID = FACTORY_ID;

    RETURN total_workers;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

-- Fonction 2: GET_NB_BIG_ROBOTS
CREATE OR REPLACE FUNCTION GET_NB_BIG_ROBOTS RETURN NUMBER IS
    total_big_robots NUMBER;
BEGIN
    SELECT COUNT(*) INTO total_big_robots
    FROM ROBOTS_HAS_SPARE_PARTS
    GROUP BY ROBOT_ID
    HAVING COUNT(SPARE_PART_ID) > 3;

    RETURN total_big_robots;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

-- Fonction 3: GET_BEST_SUPPLIER
CREATE OR REPLACE FUNCTION GET_BEST_SUPPLIER RETURN VARCHAR2 IS
    best_supplier_name VARCHAR2(100);
BEGIN
    SELECT NAME INTO best_supplier_name
    FROM BEST_SUPPLIERS
    WHERE ROWNUM = 1;

    RETURN best_supplier_name;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

-- Procédure 1: SEED_DATA_WORKERS
CREATE OR REPLACE PROCEDURE SEED_DATA_WORKERS(NB_WORKERS NUMBER, FACTORY_ID NUMBER) IS
BEGIN
    FOR i IN 1..NB_WORKERS LOOP
        INSERT INTO WORKERS_FACTORY_1 (FIRST_NAME, LAST_NAME, START_DATE)
        VALUES ('worker_f_' || i, 'worker_l_' || i, TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '2065-01-01','J'), TO_CHAR(DATE '2070-01-01','J'))), 'J'));
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An error occurred: ' || SQLERRM);
END;
/

-- Procédure 2: ADD_NEW_ROBOT
CREATE OR REPLACE PROCEDURE ADD_NEW_ROBOT(MODEL_NAME VARCHAR2(50)) IS
BEGIN
    INSERT INTO ROBOTS (MODEL)
    VALUES (MODEL_NAME);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An error occurred: ' || SQLERRM);
END;
/
